# Generated by Django 5.2.1 on 2025-05-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestInsightApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
